### PR TITLE
"struct.unpack_from" instead of "struct.unpack"

### PR DESCRIPTION
**Pull request by crash-horror**
I am not sure if this way something gets omitted, but i was getting errors on a PC running python 3.8

### CODE REVIEW

**Comment by smunaut** [comment]
Huh ? What errors ?

**Comment by crash-horror** [comment]
struct.error: unpack requires a buffer of 7 bytes for the jog

struct.error: unpack requires a buffer of 3 bytes for the battery

But for some reason i just can't reproduce the error today 🤦‍♂️

**Comment by smunaut** [comment]
Mmm ... sounds like for some reason it received messages of a different format than it expects. The unpack_from was just masking the error but not solving the underlying issue.

**Comment by crash-horror** [comment]
Thought so, but the data i got back was the same, so disregard this, and sorry for wasting your time.

**Pull request closed without merging**
